### ISSUE TITLE
The source of data and the boundaries of conversions. 

### ISSUE THREAD

**Issue by SongChujun** [sameenmaruf/Bi-MSMT#1]
Hi, would you please tell me where you find the data(I know it's from opensubtitles, but there are too many datasets, would you please tell me which one you downloaded?

BTW, it seems that all the conversions are separated a <d>, so how did you find the conversion boundaries? Are they in the source file? Thanks!

**Comment by sameenmaruf** [comment]
Please look at data/readme.md for the details about the corpus and the conversation boundaries.
